version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: vdifn_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Get Bundler
          command: gem install bundler
      - run:
          name: Configure Bundler
          command: bundle config set --local path './vendor/bundle'
      - restore_cache:
          keys:
            - agvdifn-bundle-v1-{{ checksum "Gemfile.lock" }}
            - agvdifn-bundle-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: agvdifn-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - restore_cache:
          keys:
            - agvdifn-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --check-files --cache-folder ~/.cache/yarn
      - save_cache:
          key: agvdifn-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup database
          command: bin/rails db:setup
      - run:
          name: Jest
          command: yarn test --maxWorkers=4
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Compile
          command: bundle exec rails webpacker:compile
