version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:12.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: vdifn_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Get Bundler
          command: gem install bundler
      - run:
          name: Configure Bundler
          command: bundle config set --local path './vendor/bundle'
      - restore_cache:
          keys:
            - agvdifn-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - agvdifn-bundle
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: agvdifn-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - restore_cache:
          keys:
            - agvdifn-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --check-files --cache-folder ~/.cache/yarn
      - save_cache:
          key: agvdifn-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Set up database
          command: bin/rails db:setup
      - run:
          name: Rspec
          command: bundle exec rspec
      - run:
          name: Jest
          command: yarn test --maxWorkers=4
      - run:
          name: Compile
          command: bundle exec rails webpacker:compile
