version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.0.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: vdifn_test
          POSTGRES_PASSWORD: 'password'
    executor: ruby/default
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v1
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Set up database
          command: bundle exec rails db:setup
      - run:
          name: Run rails tests
          command: bundle exec rspec
      - run:
          name: Run js tests
          command: pnpm test
      - run:
          name: Run js build
          command: pnpm build
