development:
  adapter: async

test:
  adapter: test

production: &production
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ag_vdifn_production

production:
  <<: *production
  channel_prefix: ag_vdifn_staging
